# Site settings
title: Phbai
header-img: img/home-bg.jpg
email: phbaip@gmail.com
description: ""
baseurl: ""
url: "http://phbai.github.io"
twitter_username: phbaip
github_username:  phbai
facebook_username:  com.ryan.wang
weibo_username: phbaip
zhihu_username: phbai
author: Phbai

# Build settings
markdown: kramdown

# markdown: redcarpet
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible

highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM
